config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :hoges

end

app/models/hoge.rb
class Hoge < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  http_basic_authenticate_with :name => ENV['BASIC_AUTH_USERNAME'], :password => ENV['BASIC_AUTH_PASSWORD'] if Rails.env == "production"
end

app/controllers/hoges_controller.rb
class HogesController < ApplicationController
  before_action :set_hoge, only: [:show, :edit, :update, :destroy]

  # GET /hoges
  # GET /hoges.json
  def index
    @hoges = Hoge.all
  end

  # GET /hoges/1
  # GET /hoges/1.json
  def show
  end

  # GET /hoges/new
  def new
    @hoge = Hoge.new
  end

  # GET /hoges/1/edit
  def edit
  end

  # POST /hoges
  # POST /hoges.json
  def create
    @hoge = Hoge.new(hoge_params)

    respond_to do |format|
      if @hoge.save
        format.html { redirect_to @hoge, notice: 'Hoge was successfully created.' }
        format.json { render :show, status: :created, location: @hoge }
      else
        format.html { render :new }
        format.json { render json: @hoge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hoges/1
  # PATCH/PUT /hoges/1.json
  def update
    respond_to do |format|
      if @hoge.update(hoge_params)
        format.html { redirect_to @hoge, notice: 'Hoge was successfully updated.' }
        format.json { render :show, status: :ok, location: @hoge }
      else
        format.html { render :edit }
        format.json { render json: @hoge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hoges/1
  # DELETE /hoges/1.json
  def destroy
    @hoge.destroy
    respond_to do |format|
      format.html { redirect_to hoges_url, notice: 'Hoge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hoge
      @hoge = Hoge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hoge_params
      params.require(:hoge).permit(:name, :location)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hoges_helper.rb
module HogesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/hoges/_form.html.haml
= simple_form_for @hoge, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = error_span(@hoge[:name])
  = f.input :location
  = error_span(@hoge[:location])
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), |
    hoges_path, :class => 'btn btn-default'                      |

app/views/hoges/edit.html.haml
- model_class = Hoge
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/hoges/index.html.haml
- model_class = Hoge
.page-header
  %h1= t '.title', :default => model_class.model_name.human.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:location)
      %th= model_class.human_attribute_name(:created_at)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @hoges.each do |hoge|
      %tr
        %td= link_to hoge.id, hoge_path(hoge)
        %td= hoge.name
        %td= hoge.location
        %td= l hoge.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_hoge_path(hoge), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), hoge_path(hoge), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_hoge_path, :class => 'btn btn-primary'

app/views/hoges/new.html.haml
- model_class = Hoge
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/hoges/show.html.haml
- model_class = Hoge
.page-header
  %h1= t '.title', :default => model_class.model_name.human.titleize
%dl.dl-horizontal
  %dt
    %strong
      = model_class.human_attribute_name(:name)
      \:
  %dd= @hoge.name
  %dt
    %strong
      = model_class.human_attribute_name(:location)
      \:
  %dd= @hoge.location
= link_to t('.back', :default => t("helpers.links.back")), hoges_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_hoge_path(@hoge), :class => 'btn btn-default' 
= link_to t('.destroy', :default => t("helpers.links.destroy")), hoge_path(@hoge), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/home/index.html.haml
.cover
  .cover-image{style: 'background-image: url(/images/cover.jpg)'}
  .cover-content
    .content{ data: {'0' => 'transform: translate3d(0px, 0px, 0px); opacity: 1;', '400' => 'transform: translate3d(0px, 150px, 0px); opacity: 0;'} }
      %h1
        test.bijint.com
      %h2
        まえけんテスト用です。

.post
  .post-content
    %p
      リンク：
    %p
      %a{ href: '/umaru', target: '_blank', title: 'うまる' } うまるちゃん
    %p
      %a{ href: '/tokei-onmouse', target: '_blank', title: '時計onMouse' } 時計onMouseテスト
    %p
      %a{ href: '/junior2', target: '_blank', title: '時計onMouse' } ジュニア時計テスト
    %p
      %a{ href: '/responsify-templete', target: '_blank', title: 'responsify-templete' } responsify-templete
    %p
      %a{ href: 'http://partner.bijin-tokei.co.jp', target: '_blank', title: 'BMS' } BMS
    %p
      %a{ href: 'http://www.bijint.com', target: '_blank', title: 'TOKEI' } TOKEI
    %p
      %a{ href: 'https://manage.bijint.com/console/', target: '_blank', title: 'TOKEI管理' } TOKEI管理
    .fill

:javascript
  var s = skrollr.init();

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Maeken0710Test"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    / For third-generation iPad with high-resolution Retina display:
    / Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    / For iPhone with high-resolution Retina display:
    / Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    / For first- and second-generation iPad:
    / Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    / Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
  %body
    %header
      %nav
        / user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド
        -if user_signed_in?
          / current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド
          / *_path はUserモデルを作成したときに、deviseにより自動で作成されてますので、rake routesで確認できます
          Logged in as <strong>#{current_user.email}</strong>
          =link_to "プロフィール変更", edit_user_registration_path
          |
          =link_to "ログアウト", destroy_user_session_path, method: :delete
        -else
          =link_to "サインイン", new_user_registration_path
          |
          =link_to "ログイン", new_user_session_path
    %p.notice
      = #(notice}
    %p.alert
      = #{alert}

    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "#"} Maeken0710Test
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "top", "/"
            %li= link_to "hoges", "/hoges"
            %li= link_to "Link3", "/path3"
    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "top", "/"
              %li= link_to "hoges", "/hoges"
              %li= link_to "Link3", "/path3"
          / /.well
        / /span
      / /row

      :javascript
        var _chatlio=_chatlio||[];
        !function(){var t=document.getElementById("chatlio-widget-embed");if(t&&window.React&&_chatlio.init)return void _chatlio.init(t,React);for(var e=function(t){return function(){_chatlio.push([t].concat(arguments))}},i=["configure","identify","track","show","hide","isShown","isOnline"],a=0;a<i.length;a++)_chatlio[i[a]]||(_chatlio[i[a]]=e(i[a]));var n=document.createElement("script"),c=document.getElementsByTagName("script")[0];n.id="chatlio-widget-embed",n.src="https://w.chatlio.com/w.chatlio-widget.js",n.async=!0,n.setAttribute("data-embed-version","1.3");
        n.setAttribute("data-widget-id","aaa3a8d7-cea6-416a-53cd-6b92579c45a2");
        n.setAttribute("data-start-hidden", false);
        c.parentNode.insertBefore(n,c);
        }();

      %footer
        %p © maeken 2015
    / /container

app/views/layouts/home.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Maeken0710Test"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    / For third-generation iPad with high-resolution Retina display:
    / Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    / For iPhone with high-resolution Retina display:
    / Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    / For first- and second-generation iPad:
    / Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    / Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "#"} Maeken0710Test
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "top", "/"
            %li= link_to "hoges", "/hoges"
            %li= link_to "Link3", "/path3"
    .container
      .row
        .col-lg-20
          = bootstrap_flash
          = yield
        / /span
      / /row
      %footer
        %p © maeken 2015
    / /container

    :javascript
      var _chatlio=_chatlio||[];
      !function(){var t=document.getElementById("chatlio-widget-embed");if(t&&window.React&&_chatlio.init)return void _chatlio.init(t,React);for(var e=function(t){return function(){_chatlio.push([t].concat(arguments))}},i=["configure","identify","track","show","hide","isShown","isOnline"],a=0;a<i.length;a++)_chatlio[i[a]]||(_chatlio[i[a]]=e(i[a]));var n=document.createElement("script"),c=document.getElementsByTagName("script")[0];n.id="chatlio-widget-embed",n.src="https://w.chatlio.com/w.chatlio-widget.js",n.async=!0,n.setAttribute("data-embed-version","1.3");
      n.setAttribute("data-widget-id","aaa3a8d7-cea6-416a-53cd-6b92579c45a2");
      n.setAttribute("data-start-hidden", false);
      c.parentNode.insertBefore(n,c);
      }();